export var formData = {
    personal: {
        name: '',
        surname: '',
        name_changed: false,
        changed_name: '',
        birth_date: '',
        birth_place: '',
        qualification: '',
        profession: '',
        address: '',
        residing_since: '',
        contact_no1: '',
        contact_no2: '',
    },
    family: {
        father_name: '',
        mother_name: '',
        hus_wif_name: '',
        marriage_date: '',
        government: '',
    },
    witnesses: {
        name_witness1: '',
        address_witness1: '',
        name_witness2: '',
        address_witness2: '',
    },
    payment: {
        amount: '',
        amount_affidavit: '',
        amount_total: '',
        cheque_no: '',
        bank_name: '',
    },
    other: {
        action: '',
        type: '',
        old_passport: '',
        police_station: '',
        appointment_place: '',
        form_no: '',
        telecaller_name: '',
        executive_name: '',
    },
}

export var documents = [
    {
        name: 'Aadhar Card',
        uploadName: 'aadhar.jpg',
        data: '',
        format: 'base64',
        contentType: 'image/jpeg',
    },
    {
        name: 'Pan Card',
        uploadName: 'pan.jpg',
        data: '',
        format: 'base64',
        contentType: 'image/jpeg',
    },
    {
        name: 'Bank Details',
        uploadName: 'bank_details.jpg',
        data: '',
        format: 'base64',
        contentType: 'image/jpeg',
    },
    {
        name: 'Salary Slip',
        uploadName: 'salary_slip.pdf',
        data: '',
        format: 'data_url',
        contentType: 'application/pdf',
    },
    {
        name: 'Education Details',
        uploadName: 'education.xls',
        data: '',
        format: 'data_url',
        contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    },
    {
        name: 'Customer Signature',
        uploadName: 'customer_signature.jpg',
        data: '',
        format: 'data_url',
        contentType: 'image/jpeg',
    },
    {
        name: 'Executive Signature',
        uploadName: 'executive_signature.jpg',
        data: '',
        format: 'data_url',
        contentType: 'image/jpeg',
    },
]